### PR TITLE
Wrapper Ads Support, HTTP Headers, allowing only 1 Ad, Fallback support.

### PR DESCRIPTION
**Pull request by stuffmc**
Also fixed a few hickups like breaking the demo because I didn't parse the `x-mp4` anymore ;-) Please check the Wrapper Ads part and let me know.

### CODE REVIEW

**Comment by stuffmc** [comment]
Added partial support for Wrapper Ads. Have a look and let me know. FYI: I personally only need "pre-roll" in my project.

**Comment by stuffmc** [comment]
Hey will you merge the other changes in Master? I'd rather use master in my current project instead of my own fork.

**Comment by kolyuchiy** [comment]
Hi! Sorry for taking so long to check your work. Sadly I don't have enough time and interest to maintain this project properly.

**Comment by stuffmc** [comment]
Awesome! Thanks. I'll need to merge your changes back since I'll have to work on the "Wrapper" part again probably today or tomorrow.

**Comment by stuffmc** [comment]
You might wanna look at my very last commit (not yet merged). Turns out your code for parsing `<InLine>` with "first element" will fail if the first element is, say, a comment ;-) I think using XPath is a better plan.

**Comment by kolyuchiy** [comment]
Yes, sure, better syntax checks are needed. Although XPath would be an overkill here. Simple `if` checks are enough IMO. But if you do XPath I won't mind.

**Pull request merged**
